using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class DS_QuestionScript : MonoBehaviour
{
    private List<string> questions;
    private List<string> spiceUpQuestions;
    private List<string> weirdQuestions;
    private List<string> ladiesNightQuestions;
    private List<string> instructions;
    private List<string> yourTurnTexts;
    private List<string> allPlayersTurnTexts;
    private List<string> allInstructions;

    // Start is called before the first frame update
    void Start()
    {
        questions = new List<string>
        {
            "what is the Capital of France?",
            "how many days does it take the moon to circle the earth?",
            "what planet is called the earth twin?",
            "who wrote the play 'Hamlet'?",
            "you have two options, 'get rich till you die' or 'become immortal', which are you choosing?",
            "if you could have dinner with any fictional character, who would it be and why?",
            "what's the most adventurous thing you've ever done?",
            "if you had a time machine, would you go to the future or the past?",
            "if you could master any instrument instantly, which would you choose?",
            "what's something silly you believed as a kid?",
            "what's one thing you would change about the world if you could?",
            "if you were famous, what would it be for?",
            "what's something people misunderstand about you?",
            "if you could invite any three people (dead or alive) to dinner, who would they be?",
            "what's your favorite way to relax after a long day?",
            "what's a new hobby or skill you'd love to learn?",
            "what's one thing you're obsessed with right now?",
            "if your pet could talk, what's the first thing they'd say about you?",
            "if you could switch bodies with anyone for a day, who would it be?",
            "what's something you could talk about for hours?",
            "what's a food you love that most people dislike?",
            "if you could be any animal, what would you be and why?",
            "what's one thing you hope to achieve in the next year?",
            "if you could make any one law, what would it be?",
            "what's the funniest prank you've ever pulled?",
            "if you could invent any holiday, what would it celebrate?",
            "what's your favorite smell, and what memory does it bring back?",
            "what's the kindest thing a stranger has ever done for you?",
            "on 3, point to the person who is most likely to be the last one ready to go out!",
            "if you could learn the truth behind one mystery, what would it be?",
            "what's a talent or skill you've always admired in others?",
            "what's your favorite way to spend a rainy day?",
            "if you could have a personal theme song play every time you entered a room, what would it be?",
            "what's something on the internet that you recently discovered and loved?",
            "if animals could talk, which one do you think would be the most annoying?",
            "if you were given a million dollars today, what's the first thing you'd do?",
            "what's your idea of the perfect day?",
            "if you were stranded on a deserted island, what three things would you bring with you?",
            "what's a song that you can't help but sing along to?",
            "what's a skill you wish you had but never learned?",
            "if you were a superhero, what would your power be, and what would be your weakness?",
            "point to the player most likely to leave the party without saying goodbye!",
            "who's the most likely in the group to have a sugar daddy?",
            "have you ever rode a horse?",
            "for the next 3 rounds your nickname is Lil Pork, anyone who doesn't call you that takes 5 strikes!",
            "what's the tallest mountain in the world?",
            "what is the capital of Japan?",
            "how many colors are there in a rainbow?",
            "how many days are there in a leap year?",
            "what's the chemical symbol for gold?",
            "who painted the Mona Lisa?",
            "what year did the Titanic sink?",
            "what's the smallest country in the world?",
            "if you were invisible for a day, what would you do?",
            "what's your favorite childhood memory?",
            "what's your dream travel destination and why?",
            "if you had a superpower for one day, what would it be?",
            "name one historical figure you'd love to meet and why.",
            "what's your most embarrassing moment?",
            "if you could only eat one food for the rest of your life, what would it be?",
            "if you could live anywhere in the world, where would it be?",
            "what's your favorite book or movie of all time?",
            "what's the best advice you've ever received?",
            "what's the most daring thing you've ever done?",
            "what's your favorite holiday and how do you celebrate it?",
            "if you could swap lives with anyone for a day, who would it be?",
            "what's one thing you're grateful for today?",
            "if you could invent something, what would it be?",
            "what's the most delicious meal you've ever had?",
            "what's your hidden talent?",
            "what's a skill you'd love to master?",
            "what's your favorite game to play with friends?",
            "if you could have dinner with one fictional character, who would it be?",
            "what's the funniest thing that's happened to you recently?",
            "what's the best gift you've ever received?",
            "if you were a piece of furniture, what would you be and why?",
            "what's your dream job?",
            "what's the one app you couldn't live without?",
            "if you could time travel, what year would you visit and why?",
            "what's your favorite pizza topping?",
            "what's one thing you've always wanted to learn?",
            "if you could live in any time period, past or future, when would it be?",
            "what's one thing on your bucket list?",
            "if you could trade places with a celebrity for a day, who would it be?",
            "what's your favorite way to spend a lazy Sunday?",
            "what's your favorite childhood cartoon?",
            "what's the first thing you'd buy if you won the lottery?",
            "who in this group is most likely to become president?",
            "what's your go-to guilty pleasure snack?",
            "if you could speak any language fluently, what would it be?",
            "what's your favorite ice cream flavor?",
            "if you could write a book, what would it be about?",
            "what's your dream car?",
            "how many cars would you want to have if money wasn't an issue?",
            "If you could redo one moment in your life, what would it be?",
            "who's the funniest person in this group?",
            "what's your biggest phobia?",
            "if you were an animal, what would you be?",
            "what's your favorite type of weather?",
            "If you could live underwater or in space, which would you choose?",
            "what's your favorite song to dance to?",
            "if you could design a video game, what would it be about?",
            "what's the weirdest dream you've ever had?",
            "if you could only watch one TV show forever, what would it be?",
            "what's the most random fact you know?",
            "if you were a superhero, what would your costume look like?",
            "what's the worst job you've ever had?",
            "if you were a kitchen utensil, what would you be?",
            "what's the best compliment you've ever received?",
            "what's your favorite midnight snack?",
            "if you could pick a new name for yourself, what would it be?",
            "what's your go-to comfort food?",
            "if you were a color, what would you be and why?",
            "what's your most prized possession?",
            "who's the most likely in this group to win a dance-off?",
            "if you could be a fly on the wall for any event in history, what would it be?",
            "if you could have any mythical creature as a pet, what would it be?",
            "what's the weirdest thing in your fridge right now?",
            "if you could instantly learn a new language, what would it be?",
            "if you were a breakfast food, what would you be?",
            "what's the most unique talent you've seen someone have?",
            "what's your favorite childhood memory involving food?",
            "if you could swap lives with anyone here for a day, who would it be?",
            "what's the funniest name you've ever heard for a pet?",
            "what's one thing you've done that you're really proud of?",
            "if you could live in any fictional world, which one would it be?",
            "what's your favorite word and why?",
            "if you had to pick one song to describe your life, what would it be?",
            "what's the best prank you've ever seen pulled?",
            "if you could create a new emoji, what would it look like?",
            "what's the silliest fashion trend you've ever tried?",
            "if you could be famous for inventing something, what would it be?",
            "if you could visit any planet, which one would it be and why?",
            "what's the most useless talent you have?",
            "what's the last thing you Googled?",
            "if you could only wear one color for the rest of your life, what would it be?",
            "what's the strangest compliment you've ever received?",
            "if you could be any age forever, what age would you choose and why?",
            "what's your go-to movie quote?",
            "if you could meet your future self, what would you ask them?",
            "what is the largest planet in our solar system?",
            "which country is known as the Land of the Rising Sun?",
            "what element does 'O' represent on the periodic table?",
            "what is the capital of Canada?",
            "what's the smallest country in the world?",
            "in which year did the Titanic sink?",
            "Who wrote the Harry Potter series?",
            "what is the hardest natural substance on Earth?",
            "who discovered penicillin?",
            "what is the national sport of Japan?","What is the national sport of Japan?",
            "which planet is known as the Red Planet?",
            "what's the name of the largest desert on Earth?",
            "which animal is known as the King of the Jungle?",
            "what is the currency of the United Kingdom?",
            "what type of animal is the fastest land mammal?",
            "which animal is the largest mammal on Earth?",
            "what is the smallest ocean in the world?",
            "who was the first person to set foot on the Moon?",
            "which country invented the first airplane?",
            "what is the capital of Brazil?",
            "which country is known for its pyramids?",
            "which country is known for its lions?",
            "what's the hardest rock in the world?",
            "in what city would you find the famous landmark, the Eiffel Tower?",
            "in which continent is the Sahara Desert located?",
            "what is the world's most populous country?",
            "what is your country's most populous city?",
            "which planet is closest to the Sun?",
            "which country's flag features a red maple leaf?",
            "which ocean is the largest by surface area?",
            "what is the largest island in the world?",
            "what is the national flower of Japan?",
            "in which city would you find the famous landmark, the Colosseum?",
            "which continent has the most countries?",
            "what is the smallest country in the world?",
            "who invented the light bulb?",
            "which animal is known for its black and white stripes?",
            "what's the capital of Italy?",
            "name ten football clubs",
            "which country is home to the Great Barrier Reef?",
            "which famous explorer is credited with discovering America?",
            "who wrote the novel '1984'?",
            "which city is known as the Big Apple?",
            "which fruit has its seeds on the outside?",
            "what was the first man-made object to reach the moon?",
            "Which fruit is known as the king of fruits?",
            "Which city hosted the 2016 Summer Olympics?",
            "name two planets closest to the earth"
        };

        spiceUpQuestions = new List<string>
        {
            "what's the most attractive thing about a person—looks or personality?",
            "if you could take anyone here to anywhere in the world right now, who would it be?",
            "if you played truth or dare, what's the first question you'd ask?",
            "if you had to write a flirty pickup line right now, what would it be?",
            "would you rather have a candlelit dinner or a fun night at an amusement park?",
            "if you were being dared to send a risky text to your crush right now, would you do it?",
            "what's your idea of the perfect first date?",
            "if you were given three wishes and you had to use one on anyone here, what would it be?",
            "would you rather cuddle under the stars or dance in the rain?",
            "would you rather receive a romantic love letter or a surprise adventure date?",
            "would you rather kiss in the moonlight or at sunrise?",
            "would you rather be caught staring at your crush or accidentally send them a flirty text?",
            "would you rather go on a blind date or confess your crush to someone you barely know?",
            "would you rather have a secret admirer or be someone's secret crush?",
            "would you rather be complimented for your looks or your intelligence?",
            "would you rather have an intense staring contest with your crush or play 20 questions with them?",
            "would you rather have a mysterious secret admirer or a very obvious one?",
            "would you rather spend a whole night talking or share one unforgettable kiss?",
            "what's the boldest move you've ever made on someone you liked?",
            "have you ever had a crush on someone you shouldn't have?",
            "what's the most unexpected place you've flirted with someone?",
            "have you ever had a dream about someone in this room?",
            "if you could only use one flirty emoji for the rest of your life, which would it be?",
            "describe your type—but don't make it obvious if it's someone in this game.",
            "have you ever sent a text and immediately regretted it?",
            "if you were being dared you to send a winking selfie to someone, who would you send it to?",
            "what's your most ridiculous pickup line that actually worked?",
            "would you rather go on a mystery date or plan the perfect romantic surprise for someone?",
            "do you believe in love at first sight, or do you think love needs time?",
            "what's one romantic gesture?",
            "what's one romantic gesture that always melts your heart?",
            "if you could go back in time and change one romantic decision, would you?",
            "do you think soulmates exist, or is love just about timing?",
            "what's the best compliment you've ever received?",
            "if you could only choose one way to express love—words, actions, or gifts—what would it be?",
            "what's one thing that instantly makes someone more attractive?",
            "if you were in a movie, what would your story be?",
            "do you believe in destiny when it comes to love?",
            "what's your guilty pleasure when it comes to romantic?",
            "if you were asked to describe your crush using only one emoji, which would you pick?",
            "have you ever written a love letter?",
            "if you had to create a flirty playlist, what song would be first on it?",
            "have you ever gone on a date just because you were bored?",
            "if I dared you to send me a voice note saying something cute, would you do it?",
            "what's the most unexpected place you've had a romantic moment?",
            "have you ever been caught flirting when you weren't supposed to?",
            "what's your go-to move when you like someone?",
            "if you could have any superpower, but it had to be useless in combat, what would you choose?",
            "if you could trade lives with any fictional character, who would it be?",
            "if you could wake up tomorrow fluent in any language, which one would you pick?",
            "what's the most ridiculous thing you've ever done to impress someone?",
            "what's a song lyric that perfectly describes your love life?",
            "if your love life was a reality show, what would it be called?",
            "if we had to choose a couple's costume for Halloween, what should we be?",
            "if your dating history was a movie genre, what genre would it be?",
            "what's one thing that instantly makes you smile swoon?",
            "if you had to make a flirty nickname for me right now, what would it be?",
            "if you were given a one-minute free pass to do anything to someone here, what would you do?",
            "if you were dared to kiss someone here anywhere except their lips, where would it be?",
            "what's the naughtiest thing you've ever done with someone?",
            "if you had to make someone here blush in three words, what would you say?",
            "would you rather have a steamy makeout session in public or a wild night in private?",
            "would you rather be blindfolded or have your hands tied up?",
            "would you rather play 'Truth or Strip' or 'Dare or Kiss'?",
            "would you rather be caught making out or catch someone making out with your crush?",
            "would you rather have a shower together or a bath together?",
            "would you rather kiss slow and deep or hot and fast?",
            "have you ever thought about someone here in bed?",
            "what's your favorite thing to do with someone behind closed doors?",
            "describe your first kiss",
            "describe your first sex",
            "have you ever had a one-night stand?",
            "what's the sexiest thing someone has ever said to you?",
            "if you were given 30 seconds to touch someone here anywhere, where would you start?",
            "have you ever gotten caught doing something you shouldn't have?",
            "what's the wildest text you've ever sent?",
            "if you could have anyone you like here for one night, how would you want it to go?",
            "have you ever sexted someone?",
            "what's the most fun you've had in the dark?",
            "what's one fantasy you've always wanted to try?",
            "where's the craziest place you've ever made out?",
            "what's your favorite type of kiss?",
            "have you ever been so tempted by someone that you couldn't resist?",
            "what's the hottest thing about you?",
            "if you were asked to teach how to kiss, how would you do it?",
            "have you ever been kissed so good you forgot everything else?",
            "have you ever been so close to crossing the line but stopped yourself?",
            "who in this group would you love to be trapped in a room with for an hour?",
            "if you had to cuddle with someone here tonight, who's getting the invite?",
            "who in this room do you think would be the best at kissing?",
            "who would you let steal a kiss from you right now—no questions asked?",
            "if someone had to take you on a date right now, who would you want it to be?",
            "what's one flirty compliment that would instantly make you melt?",
            "who here do you think has the most kissable lips?",
            "slow and sensual or fast and passionate—what's your ideal kiss?",
            "if someone had to describe your most irresistible trait, what would it be?",
            "have you ever had a secret crush on someone in this group?",
            "what's the most unforgettable kiss you've ever had—and would you do it again?",
            "if someone here whispered something naughty in your ear, who would you want it to be?",
            "what's one move that always leaves you weak in the knees?",
            "what's the most daring thing you've done just because you were attracted to someone?",
            "what's the first thing you notice when someone catches your eye?",
            "if someone here had to sing you a love song, who's getting the mic?",
            "if you could have one person here give you a full-body massage, who would you choose?",
            "romantic candlelit dinner or sneaky, steamy adventure—which one excites you more?",
            "what's one way someone could instantly make your heart race?",
            "if someone here locked eyes with you for ten seconds, who would you want it to be?",
            "who in this group do you think gives the kind of hugs that make you never want to let go?",
            "if someone had to flirt with you right now, who would make you blush the most?",
            "what's the most heart-racing text you've ever received?",
            "who in this room do you secretly think is the best kisser?",
            "what's one way to completely steal your attention in a room full of people?",
            "if you had to let someone here plan a surprise date for you, who's in charge?",
            "who here do you think has the smoothest, most charming vibe?",
            "have you ever had a spicy dream about someone in this group?",
            "what's the sexiest thing someone could whisper to you right now?",
            "if someone had to sweep you off your feet in the boldest way, what would they do?",
            "who in this room do you think knows how to keep a secret... and who doesn't?",
            "if you could only flirt with one person in this room for the next 24 hours, who's the lucky one?",
            "what's a fun, flirty challenge you'd love to see happen right now?",
            "who in this group do you think would go all out to impress their crush?",
            "what's the boldest, riskiest thing you've done to get someone's attention?",
            "if someone in this room had to dress you up for a sexy night out, who would you trust?",
            "what's one thing that instantly makes you see someone as ridiculously attractive?",
            "if you had to let someone here give you a dare—no matter what—who's choosing it?",
            "what's one playful thing someone could do that would make you completely melt?",
            "if someone in this group had to dedicate a love song to you, who would you want it to be?",
            "have you ever felt an undeniable spark the first time you met someone?",
            "if you had to take a dance class with someone here, who would you want as your partner?",
            "who in this group would absolutely dominate a flirting contest?",
            "what's the most unexpected, bold place you've ever flirted with someone?",
            "if you had to fall into someone's arms right now, who would you pick?",
            "what's the sweetest, most thoughtful thing someone has ever done to make you feel special?",
            "if you could relive one steamy or romantic moment, which one would it be?",
            "who in this room do you think would give the best surprise gift with a personal touch?",
            "what's the most breathtakingly romantic thing you've ever experienced?",
            "if someone here had to pick your next date and keep it a surprise, who would you trust?",
            "what's the most tempting thing about the person next to you right now?",
            "if someone here were to steal a kiss from you, who would you hope it is?",
            "what's one thing that instantly turns you on?",
            "describe your ideal make-out session in three words.",
            "what's something you've imagined doing with someone in this group?",
            "if a secret admirer from this group confessed right now, how would you react?",
            "who in this group do you think gives the best hugs… or more?",
            "what's the naughtiest thought you've had about someone here?",
            "if you had to pick someone here for a midnight adventure, who would it be?",
            "what's something you've been dying to try but need the right partner for?",
            "who here do you think would be the best in bed, and why?",
            "if someone here asked you for a private night, no strings attached, would you say yes?",
            "which person here do you think has the kind of kiss that would leave you wanting more?",
            "what's the one thing you'd do if you knew no one would ever find out?",
            "if someone here dared you to let go and live in the moment, who would you trust enough to do it with?",
            "what's the sexiest thing about you that you're keeping a secret from everyone here?",
            "who would you want to share a hot, steamy night with, no questions asked?",
            "have you ever thought about what it'd be like to be with someone in this group, and who?",
            "what's one thing about you that would make someone beg for more?",
            "if you were locked in a room with someone here, how long before things got... heated?",
            "who here would you love to be pinned against a wall by, and why?",
            "what's the most scandalous fantasy you've had about someone in this group?",
            "who do you think would make you lose control if you spent one night alone with them?",
            "what's the one thing you've wanted to try with someone but haven't had the guts to ask?",
            "if you were told you could have one night with anyone here, no rules, no regrets, who would it be?",
            "who in this group could make you forget your own name in the heat of the moment?",
            "what's the wildest thing you'd do if someone here whispered in your ear right now?",
            "who do you think you could get to do exactly what you wanted, just with a look?",
            "if someone told you they wanted to explore every inch of you tonight, how would you respond?",
            "what would it take for you to let someone here tie you up and take control?",
            "who in this group do you think could make you scream their name without even trying?",
            "what's the one thing that would make you drop all your walls with someone here?",
            "if someone here wanted to take full control tonight, how long before you gave in?",
            "who do you think could make you forget everything but them in bed?",
            "what's one thing you'd let someone here do to you, no questions asked?",
            "if someone here whispered the dirtiest thing they could think of, how would you react?",
            "what's the most intimate thing you've wanted to do with someone here but haven't yet?",
            "who would you want to rip your clothes off and leave you breathless in the best way possible?",
            "if you were told to leave this place right now and go somewhere private with someone, who would you choose?",
            "what's the first thing you'd do if someone here told you they wanted to make you theirs for the night?",
            "who here would you love to be tied up by and have their way with you?",
            "what's the most taboo fantasy you've ever had about someone in this group?",
            "if you were locked in a room with someone here, who would you let take control?",
            "who could you see yourself getting caught up in a hot, no-strings-attached fling with?",
            "what's one thing you would want to try in bed that you haven't yet?",
            "who in this group do you think has the potential to drive you wild?",
            "what's the dirtiest thing you've ever thought about doing with someone here?",
            "if someone here gave you a sexy look, how would you respond?",
            "who do you think would make you moan their name in seconds?",
            "if you could have one night of passion with someone here, no consequences, who would it be?",
            "what's one thing you've wanted to say to someone in this group but haven't yet?",
            "who do you think would leave you breathless in less than five minutes?",
            "what's something naughty you've thought about doing with someone here in secret?",
            "if you were to kiss someone here right now, who would it be and how?",
            "who here do you think could turn you into their personal playground?",
            "if someone here pulled you in for a kiss right now, would you kiss back?",
            "who here do you think would make the best lover?",
            "what's the first thing you would do if someone here invited you to a private room?",
            "who here would you love to take home and make them yours for the night?",
            "what's the most intimate thing you've wanted to do with someone in this group?",
            "who in this group has the best chance of making you forget your own name?",
            "what's the one thing you're dying to explore with someone here?",
            "who would you trust enough to share your deepest desires with?",
            "what would it take for you to invite someone here into your bed tonight?",
            "who in this group do you think would make you lose all control?",
            "what's the most seductive move you've seen someone do here?",
            "who here has the kind of energy that makes you feel all sorts of things?",
            "what's one thing that always turns you on when you're around someone here?",
            "who in this group do you think has the most irresistible touch?",
            "if you had to choose one person here to seduce you, who would it be and why?",
            "who do you think would make the best partner for a wild night of no strings attached?",
            "what's the most dangerous thing you've done for the thrill of it?",
            "who would you love to wake up next to after a night of passion?",
            "what would you do if someone here grabbed you and kissed you passionately?",
            "who in this group could make you lose all sense of time with just one touch?",
            "what's the naughtiest thing you'd let someone here do to you?",
            "who in this group do you think has the perfect body to match their confidence?",
            "what's something you've secretly imagined doing with someone here?",
            "if someone here told you they wanted to have a private moment with you, would you go?",
            "who would you love to let completely take control of you for an unforgettable night?",
            "who here could make you scream in pleasure with just their hands?",
            "what's one fantasy you've had about someone here that would shock them?",
            "if you could get away with anything with someone in this group, what would it be?",
            "who do you think here would love to see you in a more... vulnerable state?",
            "if someone here asked to spend the night with you, no questions asked, how would you react?",
            "what's the sexiest thing you've ever seen someone do here?",
            "who would you want to explore the most intimate parts of you?",
            "what's one thing that would make you want to rip someone's clothes off instantly?",
            "who here would you love to have an unforgettable, steamy moment with, no regrets?",
            "what's one dirty secret you'd share with someone here if the moment was right?"
        };
        
        weirdQuestions = new List<string>
        {
            "what's the weirdest thing you've ever eaten on purpose?",
            "have you ever talked to an inanimate object as if it could respond?",
            "what's the most ridiculous lie you've ever told and gotten away with?",
            "have you ever danced alone in front of a mirror like no one was watching?",
            "what's the strangest dream you've ever had that still makes no sense?",
            "have you ever sung a song in a totally made-up language?",
            "what's the weirdest thing you've ever Googled?",
            "have you ever worn mismatched shoes or socks in public on purpose?",
            "what's the most unusual thing you've ever collected?",
            "have you ever smelled something strange just to know what it was like?",
            "what's the weirdest conversationyou've ever overheard?",
            "have you ever tried to communicate with an animal and believed it understood?",
            "what's the most bizarre excuse you've ever used to get out of something?",
            "have you ever made up a completely fake story and told it with a straight face?",
            "what's the strangest challenge you've ever attempted?",
            "have you ever eaten something without knowing what it was?",
            "what's the weirdest noise you can make?",
            "have you ever scared yourself with your own reflection?",
            "what's the funniest misunderstanding you've ever been a part of?",
            "have you ever pretended to be someone else just for fun?",
            "what's the strangest thing you've ever done in an elevator?",
            "have you ever had an imaginary friend?",
            "tell us the weirdest thing you've ever done when you were bored out of your mind.",
            "what's the strangest food you've ever tried, and what made you give it a shot?",
            "have you ever had a “what am I doing with my life moment in public? Tell us the details!",
            "what's the weirdest thing you've ever Googled that you're totally ashamed to admit?",
            "describe the most embarrassing thing you've done while trying to impress someone.",
            "what's the craziest thing you've done on a dare that you still can't believe you pulled off?",
            "ever had a weird conversation with a stranger that you still think about? Spill the tea!",
            "have you ever tried to eat something that wasn't food, just to see what it tasted like?",
            "what's the most random object you've ever convinced someone was valuable?",
            "share a time when you did something so ridiculous, even you couldn't stop laughing.",
            "tell us about the time you wore something totally ridiculous and owned it like a boss.",
            "ever accidentally sent a message to the wrong person and had to think of an excuse? What was the message?",
            "what's the weirdest nickname you've ever had, and how did you get it?",
            "have you ever danced like nobody was watching... but then realized someone was? What happened next?",
            "what's the oddest habit or quirk you have that nobody believes until they see it?",
            "tell us about the time you embarrassed yourself in the most unexpected way.",
            "what's the weirdest or most unexpected thing you've done to procrastinate?",
            "have you ever tried to pull off a joke that didn't quite land? What happened?",
            "what's the strangest dream you've had that still makes you scratch your head?",
            "what's the weirdest thing you've done just to make someone laugh?",
            "tell us about the time you tried to pull off a prank and it backfired in the funniest way.",
            "what's the most bizarre outfit you've worn in public, and what was the occasion?",
            "ever randomly burst out laughing in a situation where it was totally inappropriate? What was going on?",
            "what's the weirdest thing you've done to avoid an awkward situation?",
            "what's the strangest habit you had as a kid that makes you laugh now?",
            "tell us about the weirdest or funniest misunderstanding you've been part of.",
            "have you ever talked to an inanimate object like it could talk back? What was it?",
            "share a time when you accidentally convinced someone of a completely ridiculous fact.",
            "what's the weirdest thing you've done when you've had a little too much free time?",
            "what's the weirdest place you've ever napped, and how did you end up there?",
            "what been caught doing something that made you feel like you were in a spy movie? Tell us everything.",
            "what's the weirdest thing you've said out loud that you later regretted?",
            "have you ever pretended to know something you totally didn't know just to fit in? How did it go?",
            "what's the most embarrassing thing you've ever said to a crush?",
            "have you ever had a conversation that went so off the rails, you can't believe it happened?",
            "what's the most random thing you've Googled that you never thought you'd need to know?",
            "tell us about a time you got caught doing something ridiculous that you thought nobody would notice.",
            "ever had a conversation with someone and completely forgotten who they were mid-chat?",
            "what's the weirdest item you've ever brought to work or school?",
            "tell us about the time you tried to do something that turned out way harder than you expected.",
            "ever had an accidental encounter that felt like it belonged in a sitcom? What happened?",
            "what's the weirdest talent or trick you can do that surprises people?",
            "have you ever tried to talk your way out of something you clearly couldn't talk your way out of?",
            "tell us about the time you tried to look cool but ended up looking totally ridiculous.",
            "what's the most awkward or cringey thing you've done in front of someone you admire?",
            "ever mistaken a stranger for someone you knew, and how did you handle the awkwardness?",
            "have you ever said something that made absolutely no sense, but you kept talking anyway?",
            "what's the weirdest thing you've done to get someone's attention (in a good way or bad way)?",
            "ever thought someone was your friend... only to realize they were a complete stranger?",
            "have you ever had a full conversation with someone who wasn't even talking to you?",
            "what's the strangest way you've accidentally hurt yourself?",
            "tell us about a time when you tried to be serious, but couldn't stop laughing.",
            "ever had a random object that you swore was lucky, but you have no idea why?",
            "what's the weirdest food combination you've ever tried, and what did it taste like?",
            "tell us about the time you had to fake your way through something you had no clue about.",
            "what's the weirdest situation you've ever found yourself in with a stranger?",
            "ever walked into a room and immediately forgot why you were there? What did you do?",
            "what's the weirdest reason you've given for why you were late to something?",
            "tell us about the time you tried to act calm, but your nerves totally betrayed you.",
            "ever pulled off a weird but amazing DIY project that you still can't believe worked?",
            "have you ever accidentally caused chaos while trying to be helpful?",
            "what's the most bizarre thing you've convinced someone to believe?",
            "have you ever done something totally random just because you thought it'd be fun?",
            "tell us about a time when you completely misjudged a situation and it ended up being hilarious.",
            "would you rather have the ability to fly or become invisible?",
            "would you rather live in a mansion alone or in a tiny house with your best friends?",
            "would you rather lose your memory or lose your sense of taste?",
            "would you rather have unlimited money but no happiness, or happiness but always be broke?",
            "would you rather be able to time travel to the past or the future?",
            "what's the weirdest place you've ever found yourself talking to someone you didn't know?",
            "ever tried to get out of something by using the most ridiculous excuse? What was it?",
            "what's the weirdest or funniest thing you've said in your sleep (if anyone's ever caught it)?",
            "what's the oddest thing you've done to keep yourself entertained while waiting?",
            "ever walked into the wrong room and pretended you meant to do that?",
            "tell us about a time you made a totally random, weird decision and it ended up being awesome.",
            "what's the weirdest thing you've ever done just to avoid being bored?",
            "ever started a random dance party by yourself? How did that go down?",
            "have you ever mistaken a person for a celebrity, and how did that go?",
            "what's the weirdest thing you've ever done as a joke that turned out to be a disaster?",
            "have you ever told someone the most bizarre “fun fact” just to see their reaction?",
            "what's the weirdest way you've ever cheered someone up?",
            "tell us about a time when you did something so awkward, it actually became funny.",
            "have you ever tried to keep a straight face during a ridiculously funny situation?",
            "what's the most absurd thing you've convinced yourself was a good idea?",
            "ever messed up a simple task in the weirdest way possible?",
            "what's the strangest talent you've discovered in yourself?",
            "ever done something totally random just because you wanted to see if it would work?",
            "what's the weirdest thing you've done in a public place without thinking twice?",
            "tell us about the time you had a funny or weird mix-up with someone you've never met before.",
            "ever tried a random challenge and had it go completely sideways?",
            "what's the strangest thing you've done to kill time on a road trip?",
            "ever had a weird and unexpected encounter with someone famous (or thought you did)?",
            "what's the weirdest or most out-of-character thing you've done when you were tired?",
            "ever made an impulse decision that turned out to be hilarious?",
            "what's the most ridiculous thing you've convinced yourself to believe?",
            "tell us about a time when you totally misread a situation but it ended up being fun.",
            "ever had a complete mix-up with directions and ended up somewhere hilarious?",
            "what's the weirdest thing you've ever done to stand out in a crowd?",
            "ever pulled off an amazing stunt and laughed the whole time because it was so ridiculous?",
            "have you ever made an epic fool of yourself trying to look cool? Tell us about it!",
            "what's the strangest thing you've done just to avoid talking to someone?",
            "ever made a completely random decision and surprised everyone, including yourself?",
            "what's the most random thing you've spent hours doing for no reason?",
            "tell us about a time you did something absurd, and now you can't stop laughing about it.",
            "what's the weirdest thing you've ever done in a public restroom that makes you question your life choices?",
            "ever walked into a room and totally forgot why you were there, then decided to just... pretend like you knew what you were doing?",
            "what's the strangest, most random object you've used as a weapon in an emergency situation?",
            "tell us about the weirdest, most awkward silent moment you've had with a group of people where nobody knew what to do!",
            "ever started singing a song in public just because you felt it, but then realized half the crowd was watching?",
            "what's the weirdest thing you've tried to convince yourself to believe, just to make yourself feel better about something?",
            "have you ever randomly decided to impersonate a celebrity... and then somehow got away with it for way too long?",
            "what's the weirdest thing you've said to someone without realizing they weren't who you thought they were?",
            "ever been so awkward around someone you forgot how to speak entirely? How did that moment go down?",
            "what's the craziest thing you've done to escape an awkward situation, but it only made it 10 times worse?",
            "ever told a total stranger your deepest secret because you thought they were someone else? What happened next?",
            "what's the weirdest hobby you've picked up that made absolutely no sense to anyone, including yourself?",
            "have you ever done something so random and spontaneous that nobody believed you did it? What was it?",
            "what's the weirdest thing you've convinced your friends to do just because you were feeling adventurous?",
            "ever ended up at a party and did something so bizarre you're still trying to figure out how it even happened?",
            "have you ever tried to start a dance craze... only to realize it was just you dancing like a maniac?",
            "what's the strangest thing you've done just to make a moment feel “normal” when everything around you was chaos?",
            "ever sent a message you meant to send to one person, but accidentally sent it to your boss? What happened afterward?",
            "what's the weirdest, most absurd thing you've ever said to someone during an awkward silence?",
            "have you ever been part of a conversation that spiraled into total madness, and you just went with it because why not?",
            "ever done something so ridiculous, you honestly thought you were in a dream?",
            "what's the craziest thing you've done in an attempt to “fit in,” and did it work or make things way worse?",
            "tell us about the time you started laughing at something, and then couldn't stop, and no one else understood why.",
            "ever tried to play it cool, but ended up doing something super embarrassing instead? What was your “cool” moment gone wrong?",
            "what's the weirdest place you've ever been when you didn't want to be, and what was going on there?",
            "have you ever tried to impress someone by doing something completely out of character? How did it go down?",
            "ever had an absolute “WTF” moment where you had no idea how you ended up in that situation?",
            "what's the weirdest food combo you've tried and said, “Eh, this is actually not that bad”?",
            "ever tried to fake a skill (like dancing, singing, or acting) but completely butchered it in front of a crowd?",
            "tell us the wildest, most random thought you've ever had that made you question your own sanity.",
            "ever done something so embarrassing, you had to convince people you were playing a character and not just being you?",
            "what's the most out-of-character thing you've done just to shock your friends?",
            "have you ever done something really random and got caught in the middle of it with a crowd watching?",
            "what's the craziest, most illogical thing you've done for a laugh... that turned into a disaster?",
            "ever caught yourself doing something so weird that you immediately tried to pretend it didn't happen?",
            "tell us about the time you randomly decided to throw caution to the wind and do something completely unexpected.",
            "what's the weirdest attempt you've made to fit in with a group, and how did it fail spectacularly?",
            "ever pretended you knew something totally obscure just to sound impressive, but it backfired terribly?",
            "what's the weirdest thing you've done that made your friends genuinely question your sanity?",
            "ever been on the receiving end of an embarrassing prank that completely went over your head?",
            "ever tried to give someone a gift and ended up just making things awkward instead?",
            "what's the most insane, wild unplanned adventure you've had that turned into a memorable story?",
            "what's the most out-of-the-box thing you've ever done to break the ice with someone?",
            "tell us about the time you started a conversation that made absolutely no sense, but everyone went with it anyway.",
            "ever created an absolute disaster by attempting a simple task in the weirdest way possible?",
            "what's the weirdest lie you've told on the spot just to get out of something, and did anyone believe it?",
            "have you ever tried to be a clutch hero, but totally messed up at the moment you needed to be cool?",
            "ever done something so outlandish that even you have no idea why you did it?",
            "what's the most random thing you've bought just because it seemed hilarious at the time?",
            "tell us the weirdest lie you've ever told a stranger to get out of an uncomfortable situation.",
            "have you ever done something so random and hilarious, you couldn't believe you were the one doing it?",
            "ever had a situation where you tried to sound like an expert on something, but everyone could tell you were just making it up?",
            "what's the most bizarre thing you've done to try to befriend someone you barely knew?",
            "ever tried something so wild that you surprised yourself with how cool it turned out?",
            "what's the weirdest “Why not?” decision you've made that ended up being an unforgettable moment?",
            "ever randomly invented a completely new word or phrase just to see how it would sound? Did anyone pick it up?",
            "have you ever had a full-on mini-crisis over the most random thing? What happened?",
            "tell us about the time you totally embarrassed yourself by overestimating your abilities.",
            "what's the weirdest thing you've done to try and get out of a conversation you didn't want to be in?",
            "ever tried to be part of a “cool” trend, but ended up so far out of the loop it was painful?",
            "what's the most outlandish excuse you've ever given for why you couldn't show up somewhere?",
            "tell us about the most awkward thing you've done at a party just because you were feeling too much like yourself.",
            "ever been in a situation where you didn't know what was going on, so you just acted like you did?",
            "have you ever pulled off the weirdest thing, and then spent the next few hours trying to figure out why?",
            "what's the weirdest prank you've ever pulled off, or had pulled on you?",
            "ever tried to play a joke on someone but got caught up in the joke so much that it got way out of hand?",
            "what's the weirdest thing you've said to someone just to test their reaction?",
            "tell us the funniest “I can't believe I'm doing this” moment you've had recently.",
            "ever ended up in an unexpectedly funny situation because you were just trying to “go with the flow”?",
            "what's the most random thing you've ever tried just because you were feeling daring?",
            "ever walked into a place and instantly regretted it because the weirdness hit you hard?",
            "what's the weirdest thing you've done to create a memorable first impression?",
            "what's the weirdest thing you'd do for a dare right now, no questions asked?",
            "if you could make any animal here suddenly talk, who would it be and what would they say?",
            "what's something you've always wanted to try but thought it was too weird to ask?",
            "if you were stuck in an alternate dimension, which person here would you want to be stuck with, and why?",
            "what's the strangest thing you'd be willing to try on a first date?",
            "if you could swap lives with anyone here for a day, who would it be and what's the first weird thing you'd do?",
            "would you let someone here paint your face in a weird design for 24 hours for a million dollars?",
            "if you had to describe yourself as a fruit, what fruit would you be and why?",
            "if you were suddenly a superhero with an utterly strange power, who here would be your sidekick?",
            "if you could communicate with only one body part for a day, which one would it be and why?",
            "what's the most bizarre talent you have that no one here knows about?",
            "if you could only wear one color for the rest of your life, what color would you choose and how weird would it look on you?",
            "would you be willing to eat a mystery food here that's been disguised in a weird way?",
            "if you had to design the world's weirdest amusement park, what's the one ride you'd definitely include?",
            "if you could morph into any object for an hour, what would you become and why?",
            "what's the weirdest thing you'd ask someone to do if they gave you a free pass?",
            "if you could only speak in animal noises for a day, which animal would you choose to communicate like?",
            "what's the oddest thing you've Googled recently that made you laugh?",
            "the ability to be invisible only when you're dancing or have super strength only when you're wearing socks, which and why?",
            "what's the strangest combination of food you've ever eaten, and did it actually taste good?",
            "if you could put yourself in any video game world, what's the weirdest character you'd want to be?",
            "would you wear a full-body costume of your least favorite animal for a week for a million dollars?",
            "if you had to wear a ridiculously oversized hat everywhere, what would it look like?",
            "what's the weirdest thing you've ever done in a public place and gotten away with?",
            "if you could only communicate using emojis for a day, which three would you use the most?",
            "what's one weird habit you've picked up that you could never explain to someone?",
            "if you had to live in a house made entirely of one food, what food would it be?",
            "would you rather have to sing everything you say for a day or act out every conversation?",
            "if you could swap lives with any object in the room for a day, which one would it be, and what would you do?",
            "if you could have any animal's legs, which animal would you pick, and how would you move?",
            "would you rather have fingers made of spaghetti or hair that grows out of your ears?",
            "if you could only wear clothes made out of food, what food would you choose and why?",
            "if you were an alien visiting Earth for the first time, what would be the first thing you’d find totally bizarre?",
            "what's the weirdest thing you've seen someone wear that made you think, 'I need to try that?'",
            "if you could speak only in song lyrics for a day, which song would you choose to use for every situation?",
            "what's the strangest thing you would do if you suddenly woke up in the body of a rockstar?",
            "if you had a pet cactus, what would you name it, and how would you take care of it?",
            "if you could only communicate using interpretive dance for the next hour, how would you tell someone you're hungry?",
            "would you rather have to constantly hop around like a frog or walk backward everywhere for the rest of your life?",
            "if your favorite food suddenly turned into a living creature, what would it look like, and would you still eat it?",
            "if you could turn any inanimate object into a pet, which one would it be, and how would you take it on walks?",
            "what's the weirdest conversation you've ever had with a stranger in public?",
            "if you could speak to plants, what would you say to your houseplant right now?",
            "would you rather be able to shoot spaghetti out of your hands or be able to create portals through your belly button?",
            "what's the weirdest superstition you've ever heard of that you secretly find intriguing?",
            "if you could switch your body with anyone here for 24 hours, who would it be, and what weird thing would you do in their body?",
            "what's the most bizarre thing you could do with an inflatable pool toy that would leave people confused?",
            "if you had to live in a world made of clouds, what would your cloud house look like, and what would you do all day?",
            "would you rather have to wear a suit made entirely of rubber ducks or a coat made of spaghetti noodles for a week?",
            "if you had to be a walking billboard for one thing for the rest of your life, what would it advertise?",
            "would you rather fight a thousand tiny chickens or one giant hamster, and how would you prepare for it?",
            "if you could only communicate using animal noises for a day, which animal would you choose, and why?",
            "if you had a time machine, would you go to the future or the past, but only if you had to live as a celebrity in that time?",
            "if you could wear a new costume every day but it was always based on your mood, what would you be wearing right now?",
            "what's the weirdest food combination you secretly enjoy that you think people would judge you for?",
            "if you could live in a world made of candy, what candy would you want everything to be made of, and why?",
            "would you rather your hair could only be styled using pizza toppings or only ever be styled with glitter?",
            "if you could shrink down to the size of a pencil, what's the first strange thing you would do?"

        };

        ladiesNightQuestions = new List<string>
        {
            "what's the most spontaneous thing you've done with your girlfriends?",
            "if you could live in any movie or TV show, which one would it be and why?",
            "what's your go-to karaoke song that always gets you hyped?",
            "who's your ultimate girl crush, celebrity or otherwise?",
            "what's the best piece of advice a woman has ever given you?",
            "what's one thing you've learned about yourself in the last year?",
            "if you could switch lives with any woman for a day, who would it be?",
            "what's your signature dance move when you're feeling yourself?",
            "who's your ride-or-die girlfriend, and what makes her special?",
            "what's a beauty trend you tried but immediately regretted?",
            "what's your guilty pleasure TV show or movie you can watch on repeat?",
            "if you could only wear one color for the rest of your life, what would it be?",
            "what's your favorite way to treat yourself after a tough day?",
            "what's one outfit you feel unstoppable in?",
            "what's your favorite way to unwind after a busy week?",
            "who would you want to be your partner in crime for a secret adventure?",
            "what's your go-to comfort food on a cozy night in?",
            "what's one thing you've always wanted to try, but haven't yet?",
            "what's something you've done to make a girlfriend feel extra special?",
            "what's your favorite 'girl power' anthem or song?",
            "what's one beauty product you can't live without?",
            "what's your favorite girls' night out memory?",
            "if you could go on a shopping spree anywhere in the world, where would it be?",
            "what's your go-to drink order when you're out with the girls?",
            "what's the most outrageous fashion choice you've ever made?",
            "what's your favorite way to spend a lazy Sunday afternoon?",
            "who's your girl squad, and what's your bond like?",
            "what's the most thoughtful gift you've ever given a friend?",
            "what's a bad habit you're trying to break, but can't?",
            "what's your all-time favorite beauty hack?",
            "what's something you'd tell your younger self about friendships?",
            "what's the most fun adventure you've had with your girlfriends?",
            "what's a beauty trend you can't get behind?",
            "what's the best girl's trip you've ever taken?",
            "what's the most embarrassing thing that's happened to you on a girls' night?",
            "what's one thing you've always wanted to do but are too afraid to try?",
            "who do you call when you need someone to talk to no matter what?",
            "what's your ultimate self-care ritual after a stressful day?",
            "what's one celebrity you would totally fangirl over if you met them?",
            "what's the funniest thing a friend has ever done that you'll never forget?",
            "what's the one thing you always carry in your purse, no matter what?",
            "what's your signature scent, and why do you love it?",
            "what's a guilty pleasure that never fails to cheer you up?",
            "what's the best piece of advice your mom or grandma ever gave you?",
            "what's your dream girl's night in movies, snacks, and all?",
            "what's the one thing you love most about being a woman?",
            "what's the craziest thing you've done for a friendship?",
            "what's one trend you're excited to try but haven't yet?",
            "what's your favorite thing to do with a girlfriend when you need to vent?",
            "what's the best compliment you've ever received from a friend?",
            "what's your idea of the perfect brunch with the girls?",
            "what's the worst date you've ever been on, and how did you survive it?",
            "what's your biggest pet peeve in a friendship?",
            "who in your life inspires you the most, and why?",
            "what's your go-to pick-me-up when you're feeling down?",
            "what's the most epic girls' night out you've ever had?",
            "what's the funniest meme or joke that always makes you laugh?",
            "what's your favorite way to celebrate a successful day with your girlfriends?",
            "what's the most outrageous thing you've done on a girls' trip?",
            "what's your guilty pleasure snack that you cant resist?",
            "what's one thing you'd love to learn or master just for fun?",
            "what's the most fun thing you've done to pamper yourself?",
            "what's the first thing you do when you wake up in the morning?",
            "who's the first person you text when you have exciting news?",
            "what's the best gift you've ever received from a friend?",
            "what's one quirky thing about you that your friends love?",
            "what's the most embarrassing thing you've done while dancing?",
            "what's one thing that always makes you laugh no matter what?",
            "what's your dream vacation with your best friends?",
            "what's the craziest hairstyle you've ever tried?",
            "what's one thing that instantly boosts your confidence?",
            "what's your go-to dance move when you're feeling yourself?",
            "what's the best way to spend a Sunday afternoon with the girls?",
            "who's the one friend who always knows how to make you smile?",
            "what's the best beauty advice you've ever gotten?",
            "what's something you've always wanted to try but have never gotten around to?",
            "what's one thing that makes you feel like a million bucks?",
            "what's your ultimate guilty pleasure when you're having a lazy day?",
            "what's the best advice you've gotten about dating or relationships?",
            "what's the best secret you've shared with a girlfriend?",
            "what's the most fun thing you've done for a girlfriend's birthday?",
            "what's the one fashion trend you wish you could pull off?",
            "what's the silliest thing you've done when you were in a good mood?",
            "what's your favorite way to unwind after a long week?",
            "who would you love to spend a weekend getaway with and why?",
            "what's one movie or TV show you can watch over and over again?",
            "what's your secret talent that no one knows about?",
            "what's the craziest thing you've done on a whim?",
            "what's your favorite thing to do with your best friend when you're feeling adventurous?",
            "what's your idea of a perfect girls' night in, from start to finish?",
            "what's the best compliment you've ever received from another woman?",
            "what's something fun and silly you'd do if you were feeling bold?",
            "what's one thing you wish every woman knew about herself?",
            "what's the last thing you Googled out of curiosity?",
            "what's your favorite self-care ritual after a long week?",
            "what's the most ridiculous thing you've done for a laugh?",
            "what's your ideal girls' weekend getaway destination?",
            "what's the weirdest thing you've done just because it seemed fun?",
            "what's one silly thing you and your friends always do when you're together?",
            "what's something you always do before you leave the house?",
            "what's the craziest fashion trend you've ever rocked and loved?",
            "what's your all-time favorite girls' night activity?",
            "what's the funniest thing you've ever done with your girlfriends?",
            "what's your ultimate girls' night snack that everyone loves?",
            "what's the one thing you wish you could tell your younger self?",
            "what's the wildest beauty trend you've tried just to see if it worked?",
            "what's one thing on your bucket list you can't wait to cross off?",
            "what's your secret weapon to cheer up a friend in a tough time?",
            "what's the most dramatic thing you've ever done for a laugh?",
            "what's your go-to song when you need to feel empowered?",
            "who's your celebrity girl crush and why?",
            "what's one thing that always makes you feel like a queen?",
            "what's the most heartwarming thing a friend has done for you?",
            "what's your go-to outfit when you want to feel stylish and confident?",
            "what's your favorite way to bond with your bestie?",
            "what's the most outrageous adventure you've ever been on with friends?",
            "what's your guilty pleasure that you'd never admit to most people?",
            "what's one fun thing you've always wanted to try with your girlfriends?",
            "what's one thing you could talk about for hours with your friends?",
            "what's the best way to spoil yourself after a busy week?",
            "what's the one beauty product you can't live without on a lazy day?",
            "what's the silliest thing you've done on a dare from your best friend?",
            "what's the weirdest fashion choice you've ever made that you now regret?",
            "what's your favorite thing to do when you want to relax and recharge?",
            "what's one thing your friends always come to you for advice about?",
            "what's your favorite way to pamper yourself when you're feeling extra?",
            "what's something quirky or unique about your friendship group?",
            "what's the most unforgettable trip you've taken with your best friends?",
            "what's your go-to guilty pleasure movie when you're in the mood for nostalgia?",
            "what's one thing you've always wanted to do but haven't had the courage to?",
            "what's the most random yet fun thing you and your friends have done together?",
            "what's your go-to comfort food when you need a pick-me-up?",
            "what's one wild thing you'd love to do on a girls' weekend?",
            "what's one thing you've learned about yourself through your friendships?",
            "what's the best advice you've gotten about loving yourself?",
            "what's your favorite thing to do with your girls to make lasting memories?",
            "what's the funniest text message you've ever sent to a friend?",
            "what's your idea of a perfect self-care day?",
            "what's your must-have item for a perfect girls' night?",
            "what's something you'd love to accomplish with your best friends?",
            "what's one thing you and your friends always do to cheer each other up?",
            "what's your favorite beauty ritual to feel your best?",
            "what's your go-to outfit when you want to feel cute but comfy?",
            "what's your idea of a dream girls' day out?",
            "what's your most memorable shopping spree with your best friends?",
            "what's one embarrassing thing that always makes you laugh when you think of it?",
            "what's something fun you've done to make someone else's day better?",
            "what's your favorite thing to do when you're in the mood for some nostalgia?",
            "what's the best adventure you've had with your best friend?",
            "what's your go-to playlist when you're hanging with your friends?",
            "what's your signature dance move at parties?",
            "who's your celebrity crush that you can't stop fangirling over?",
            "what's your favorite TikTok challenge you've nailed?",
            "what's the most embarrassing thing you've done to impress someone?",
            "what's one thing you wish you could do if you had a free day?",
            "what's the funniest text you've ever sent to your BFF?",
            "what's your favorite makeup trend that you can't live without?",
            "what's your dream vacation spot with your besties?",
            "what's your favorite clothing item to wear to school to feel cute?",
            "what's your go-to snack when you're binge-watching a Netflix series?",
            "what's one thing you're totally obsessed with right now?",
            "what's the funniest thing that's happened during a sleepover?",
            "what's the wildest thing you and your friends have done after curfew?",
            "what's your favorite way to relax after a long day of school?",
            "what's the craziest hairstyle you've tried just to be bold?",
            "what's the best advice a friend has given you about school?",
            "what's your secret talent no one knows about?",
            "who's your girl crush from high school or a celeb?",
            "what's the most embarrassing outfit you've worn and regretted?",
            "what's your go-to outfit when you're in a rush but still want to look cute?",
            "what's one beauty product you would never leave the house without?",
            "what's your favorite guilty pleasure TV show that you don't tell anyone about?",
            "what's one thing you and your best friend always laugh about?",
            "what's your current favorite meme or trend on TikTok?",
            "what's your dream job when you're older?",
            "what's one thing you'd love to do but are too scared to try?",
            "what's your ultimate girls' night movie marathon pick?",
            "what's the most ridiculous rumor you've ever heard about yourself?",
            "what's your favorite hairstyle for lazy days?",
            "what's one song that always gets you and your girls hyped?",
            "what's the best Snapchat filter you always use?",
            "what's the funniest thing you've done in front of your crush?",
            "what's your go-to ice cream flavor when you're treating yourself?",
            "what's one fashion trend you're loving right now?",
            "what's your favorite part of a sleepover?",
            "what's the most extra thing you've ever done to get someone's attention?",
            "what's your favorite social media platform to get inspiration from?",
            "what's one secret you and your bestie will never tell anyone?",
            "what's your dream date idea if you could plan it?",
            "what's the best thing about having a squad of girlfriends?",
            "what's the most awkward thing you've done during a video call?",
            "what's one beauty hack you swear by?",
            "what's your most cringeworthy high school moment?",
            "what's your favorite way to spend the weekend with your girls?",
            "what's the best way to cheer up your BFF when she's having a bad day?",
            "what's the most romantic thing you've seen in a movie and wish would happen to you?",
            "what's your ultimate girls' day out idea?",
            "what's the cutest thing you've done to surprise your friends?",
            "what's your favorite song to belt out in the shower?",
            "what's your guilty pleasure when it comes to online shopping?",
            "what's one thing you'd love to do with your besties that you've never done?",
            "what's one of the weirdest things you've done just to make your best friend laugh?",
            "what's the most awkward moment you've had in front of your crush?",
            "what's your dream celebrity girl squad?",
            "what's the first thing you'd buy if you had unlimited money?",
            "what's your favorite TikTok dance that you just can't stop doing?",
            "what's the most random thing you've spent money on and totally regretted?",
            "what does your ultimate 'treat yourself' day look like?",
            "what's your favorite way to spice up your Instagram feed?",
            "what's your dream birthday party idea?"
        };

        instructions = new List<string>
        {
            "three strikes should be taken.",
            "should dance for one minute.",
            "should crack a joke.",
            "should take five (5) press ups.",
            "two strikes should be taken",
            "should hop like a big froggie! Haha!",
            "should tell a secret",
            "should recite the alphabet… backward!",
            "should say 'I love you' in another language.",
            "should sing a favorite nursery rhyme.",
            "should try to balance on one foot for 10 seconds.",
            "should meow like a cat three times.",
            "should bark like a dog five times.",
            "should act like a chicken crossing the road.",
            "should do a silly dance for 30 seconds.",
            "should clap their hands 20 times as fast as possible.",
            "should jump up and down like a kangaroo.",
            "should count from 1 to 10 in a funny voice.",
            "should pretend to laugh like a villain.",
            "should draw an imaginary square in the air.",
            "should hum the first song that comes to mind.",
            "should pretend to be an airplane for 15 seconds.",
            "should spell a random word while hopping on one foot.",
            "should count how many times they can blink in 10 seconds.",
            "should name their favorite food and describe it in five words."

        };

        allInstructions = new List<string>
        {
            "should take three strikes.",
            "should each dance for one minute.",
            "should each crack a joke.",
            "should take five (5) press ups.",
            "should take five strikes.",
            "should hop like a big froggie! Haha!",
            "should each tell a secret",
            "should each sing the chorus of their favorite song.",
            "should all make their funniest face!",
            "should each act like their favorite animal.",
            "should take turns shouting a random word—no repeats!",
            "should clap their hands while hopping on one foot.",
            "should each impersonate someone famous!",
            "should all do a group dance—freestyle, of course!",
            "should each share their favorite snack choice.",
            "should all do their best evil laugh! Mwahaha!",
            "should try balancing something on their heads.",
            "should all say their name backward.",
            "should take a round of 'truth or dare'—no dodging!",
            "should each count to five in another language.",
            "should recite the alphabet… backward!",
            "should all do their best impression of a robot.",
            "should strike their best superhero pose!",
            "should each attempt a tongue twister!",
            "should create a short, funny rhyme together.",
            "should each mimic the sound of their favorite animal.",
            "should freeze like statues for a full 30 seconds.",
            "should each whistle their favorite tune—or try!",
            "should each say something nice about the person next to them.",
            "should each say something sad about the person next to them.",
            "should each say something nice about their favourite person.",
            "should make the loudest noise they can together!",
            "should each give their best pirate 'Arrrr!'",
            "should each give their best pirate 'Aye!'",
            "should all spin in circles until someone giggles.",
            "should do their best runway walk. Fierce!"
        };

        yourTurnTexts = new List<string>
        {
            "Oh! One good turn... Ha!",
            "Are you ready for this?",
            "Definitely up now, ain't ya?!",
            "Yoo.. You got this!",
            "Shoot pookie...",
            "Okay, let's have it.",
            "Bet you didn't see this coming",
            "Lucky you, haha!",
            "Here goes nothing!",
            "Oh dear, let's hear it!",
            "Can't wait, can you?",
            "Pook, shoot!",
            "The fun just got started",
            "Hey everyone, listen, you don't wanna miss this!",
            "The next victim is you, obviously! Haha!",
            "Oh snap, it's your moment! Make it count!",
            "Drumroll, please! You're up, superstar!",
            "Hold on to your hats, it's time to shine!",
            "Woohoo! All eyes on you now!",
            "Boom! Lights, camera, action!",
            "Ahh, destiny calls! Let's hear it!",
            "Are you feeling lucky? You better be!",
            "No pressure, but we're all watching!",
            "It's showtime, baby! Go for it!",
            "Ding ding ding! Your turn to dazzle!",
            "How're you feeling now?!",
            "Mic check... You're live!",
            "Ka-chow! Show us what you're made of!",
            "Whoa, the stage is all yours! Take it away!",

        };

        allPlayersTurnTexts = new List<string>
        {
            "Alright, folks! The spotlight's on all of you now—no hiding!",
            "Woohoo! It's everyone's time to shine! Let's hear it!",
            "Drumroll, please! This one's for all of you!",
            "Okay, gang, let's see what you've got together!",
            "Shoot y'all...",
            "Okay, let's have it.",
            "Bet y'all didn't see this coming",
            "Lucky folks, haha!",
            "Here goes nothing!",
            "Oh dear, let's hear it!",
            "Can't wait, can y'all?",
            "Pooks, shoot!",
            "The fun just got started",
            "Hey everyone, listen, you don't wanna miss yourselves!",
            "The next victim is everyone",
            "The floor is yours, squad! Make it epic!",
            "Y'all better bring the heat now! No slacking!",
            "Aha! It's a team effort this time. Go, go, go!",
            "The more, the merrier!",
            "Alright, party people! This question's for the entire crew!",
            "Time to huddle up, team! This one's for all of you!",
            "Okay, champs! Show us what happens when brains collide!",
            "Uh-oh, looks like everyone's in the hot seat this time!",
            "Brace yourselves, it's an all-hands-on-deck situation!",
            "Every last one of you—let's see the magic happen!",
            "It's an all-play extravaganza! Bring your A-game, everyone!",
            "Everybody's up! The pressure's shared—good luck!",
            "One question. All of you. Let's see what chaos ensues!",
            "Alright, squad, your turn as a team. Go make history!", 
        };
    }

    public string callQuestion()
    {
        int randomIndex = Random.Range(0, questions.Count);
        return questions[randomIndex];
    }

        public string callSpiceUpMode()
    {
        int randomIndex = Random.Range(0, spiceUpQuestions.Count);
        return spiceUpQuestions[randomIndex];
    }

    public string callWeirdQuestionMode()
    {
        int randomIndex = Random.Range(0, weirdQuestions.Count);
        return weirdQuestions[randomIndex];
    }

        public string callLadiesNightMode()
    {
        int randomIndex = Random.Range(0, ladiesNightQuestions.Count);
        return ladiesNightQuestions[randomIndex];
    }

    public string callYourTurnText()
    {
        int randomIndex = Random.Range(0, yourTurnTexts.Count);
        return yourTurnTexts[randomIndex];
    }

    public string callInstructionText()
    {
        int randomIndex = Random.Range(0, instructions.Count);
        return instructions[randomIndex];
    }

        public string callAllInstructionText()
    {
        int randomIndex = Random.Range(0, allInstructions.Count);
        return allInstructions[randomIndex];
    }

     public string AllPlayersTurn()
    {
        int randomIndex = Random.Range(0, allPlayersTurnTexts.Count);
        return allPlayersTurnTexts[randomIndex];
    }
}
