using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class DS_QuestionScript : MonoBehaviour
{
    private List<string> questions;
    private List<string> instructions;
    private List<string> yourTurnTexts;
    private List<string> allPlayersTurnTexts;
    private List<string> allInstructions;

    // Start is called before the first frame update
    void Start()
    {
        questions = new List<string>
        {
            "what is the Capital of France?",
            "how many days does it take the moon to circle the earth?",
            "what planet is called the earth twin?",
            "who wrote the play 'Hamlet'?",
            "you have two options, 'get rich till you die' or 'become immortal', which are you choosing?",
            "if you could have dinner with any fictional character, who would it be and why?",
            "what's the most adventurous thing you've ever done?",
            "if you had a time machine, would you go to the future or the past?",
            "if you could master any instrument instantly, which would you choose?",
            "what's something silly you believed as a kid?",
            "what's one thing you would change about the world if you could?",
            "if you were famous, what would it be for?",
            "what's something people misunderstand about you?",
            "if you could invite any three people (dead or alive) to dinner, who would they be?",
            "what's your favorite way to relax after a long day?",
            "what's a new hobby or skill you'd love to learn?",
            "what's one thing you're obsessed with right now?",
            "if your pet could talk, what's the first thing they'd say about you?",
            "if you could switch bodies with anyone for a day, who would it be?",
            "what's something you could talk about for hours?",
            "what's a food you love that most people dislike?",
            "if you could be any animal, what would you be and why?",
            "what's one thing you hope to achieve in the next year?",
            "if you could make any one law, what would it be?",
            "what's the funniest prank you've ever pulled?",
            "if you could invent any holiday, what would it celebrate?",
            "what's your favorite smell, and what memory does it bring back?",
            "what's the kindest thing a stranger has ever done for you?",
            "on 3, point to the person who is most likely to be the last one ready to go out!",
            "if you could learn the truth behind one mystery, what would it be?",
            "what's a talent or skill you've always admired in others?",
            "what's your favorite way to spend a rainy day?",
            "if you could have a personal theme song play every time you entered a room, what would it be?",
            "what's something on the internet that you recently discovered and loved?",
            "if animals could talk, which one do you think would be the most annoying?",
            "if you were given a million dollars today, what's the first thing you'd do?",
            "what's your idea of the perfect day?",
            "if you were stranded on a deserted island, what three things would you bring with you?",
            "what's a song that you can't help but sing along to?",
            "what's a skill you wish you had but never learned?",
            "if you were a superhero, what would your power be, and what would be your weakness?",
            "point to the player most likely to leave the party without saying goodbye!",
            "who's the most likely in the group to have a sugar daddy?",
            "have you ever rode a horse?",
            "for the next 3 rounds your nickname is Lil Pork, anyone who doesn't call you that takes 5 strikes!",
            "what's the tallest mountain in the world?",
            "what is the capital of Japan?",
            "how many colors are there in a rainbow?",
            "how many days are there in a leap year?",
            "what's the chemical symbol for gold?",
            "who painted the Mona Lisa?",
            "what year did the Titanic sink?",
            "what's the smallest country in the world?",
            "if you were invisible for a day, what would you do?",
            "what's your favorite childhood memory?",
            "what's your dream travel destination and why?",
            "if you had a superpower for one day, what would it be?",
            "name one historical figure you'd love to meet and why.",
            "what's your most embarrassing moment?",
            "if you could only eat one food for the rest of your life, what would it be?",
            "if you could live anywhere in the world, where would it be?",
            "what's your favorite book or movie of all time?",
            "what's the best advice you've ever received?",
            "what's the most daring thing you've ever done?",
            "what's your favorite holiday and how do you celebrate it?",
            "if you could swap lives with anyone for a day, who would it be?",
            "what's one thing you're grateful for today?",
            "if you could invent something, what would it be?",
            "what's the most delicious meal you've ever had?",
            "what's your hidden talent?",
            "what's a skill you'd love to master?",
            "what's your favorite game to play with friends?",
            "if you could have dinner with one fictional character, who would it be?",
            "what's the funniest thing that's happened to you recently?",
            "what's the best gift you've ever received?",
            "if you were a piece of furniture, what would you be and why?",
            "what's your dream job?",
            "what's the one app you couldn't live without?",
            "if you could time travel, what year would you visit and why?",
            "what's your favorite pizza topping?",
            "what's one thing you've always wanted to learn?",
            "if you could live in any time period, past or future, when would it be?",
            "what's one thing on your bucket list?",
            "if you could trade places with a celebrity for a day, who would it be?",
            "what's your favorite way to spend a lazy Sunday?",
            "what's your favorite childhood cartoon?",
            "what's the first thing you'd buy if you won the lottery?",
            "who in this group is most likely to become president?",
            "what's your go-to guilty pleasure snack?",
            "if you could speak any language fluently, what would it be?",
            "what's your favorite ice cream flavor?",
            "if you could write a book, what would it be about?",
            "what's your dream car?",
            "how many cars would you want to have if money wasn't an issue?",
            "If you could redo one moment in your life, what would it be?",
            "who's the funniest person in this group?",
            "what's your biggest phobia?",
            "if you were an animal, what would you be?",
            "what's your favorite type of weather?",
            "If you could live underwater or in space, which would you choose?",
            "what's your favorite song to dance to?",
            "if you could design a video game, what would it be about?",
            "what's the weirdest dream you've ever had?",
            "if you could only watch one TV show forever, what would it be?",
            "what's the most random fact you know?",
            "if you were a superhero, what would your costume look like?",
            "what's the worst job you've ever had?",
            "if you were a kitchen utensil, what would you be?",
            "what's the best compliment you've ever received?",
            "what's your favorite midnight snack?",
            "if you could pick a new name for yourself, what would it be?",
            "what's your go-to comfort food?",
            "if you were a color, what would you be and why?",
            "what's your most prized possession?",
            "who's the most likely in this group to win a dance-off?",
            "if you could be a fly on the wall for any event in history, what would it be?",
            "if you could have any mythical creature as a pet, what would it be?",
            "what's the weirdest thing in your fridge right now?",
            "if you could instantly learn a new language, what would it be?",
            "if you were a breakfast food, what would you be?",
            "what's the most unique talent you've seen someone have?",
            "what's your favorite childhood memory involving food?",
            "if you could swap lives with anyone here for a day, who would it be?",
            "what's the funniest name you've ever heard for a pet?",
            "what's one thing you've done that you're really proud of?",
            "if you could live in any fictional world, which one would it be?",
            "what's your favorite word and why?",
            "if you had to pick one song to describe your life, what would it be?",
            "what's the best prank you've ever seen pulled?",
            "if you could create a new emoji, what would it look like?",
            "what's the silliest fashion trend you've ever tried?",
            "if you could be famous for inventing something, what would it be?",
            "if you could visit any planet, which one would it be and why?",
            "what's the most useless talent you have?",
            "what's the last thing you Googled?",
            "if you could only wear one color for the rest of your life, what would it be?",
            "what's the strangest compliment you've ever received?",
            "if you could be any age forever, what age would you choose and why?",
            "what's your go-to movie quote?",
            "if you could meet your future self, what would you ask them?",
            "what is the largest planet in our solar system?",
            "which country is known as the Land of the Rising Sun?",
            "what element does 'O' represent on the periodic table?",
            "what is the capital of Canada?",
            "what's the smallest country in the world?",
            "in which year did the Titanic sink?",
            "Who wrote the Harry Potter series?",
            "what is the hardest natural substance on Earth?",
            "who discovered penicillin?",
            "what is the national sport of Japan?","What is the national sport of Japan?",
            "which planet is known as the Red Planet?",
            "what's the name of the largest desert on Earth?",
            "which animal is known as the King of the Jungle?",
            "what is the currency of the United Kingdom?",
            "what type of animal is the fastest land mammal?",
            "which animal is the largest mammal on Earth?",
            "what is the smallest ocean in the world?",
            "who was the first person to set foot on the Moon?",
            "which country invented the first airplane?",
            "what is the capital of Brazil?",
            "which country is known for its pyramids?",
            "which country is known for its lions?",
            "what's the hardest rock in the world?",
            "in what city would you find the famous landmark, the Eiffel Tower?",
            "in which continent is the Sahara Desert located?",
            "what is the world's most populous country?",
            "what is your country's most populous city?",
            "which planet is closest to the Sun?",
            "which country's flag features a red maple leaf?",
            "which ocean is the largest by surface area?",
            "what is the largest island in the world?",
            "what is the national flower of Japan?",
            "in which city would you find the famous landmark, the Colosseum?",
            "which continent has the most countries?",
            "what is the smallest country in the world?",
            "who invented the light bulb?",
            "which animal is known for its black and white stripes?",
            "what's the capital of Italy?",
            "name ten football clubs",
            "which country is home to the Great Barrier Reef?",
            "which famous explorer is credited with discovering America?",
            "who wrote the novel '1984'?",
            "which city is known as the Big Apple?",
            "which fruit has its seeds on the outside?",
            "what was the first man-made object to reach the moon?",
            "Which fruit is known as the king of fruits?",
            "Which city hosted the 2016 Summer Olympics?",
            "name two planets closest to the earth"
        };

        instructions = new List<string>
        {
            "three strikes should be taken.",
            "should dance for one minute.",
            "should crack a joke.",
            "should take five (5) press ups.",
            "two strikes should be taken",
            "should hop like a big froggie! Haha!",
            "should tell a secret",
            "should recite the alphabet… backward!",
            "should say 'I love you' in another language.",
            "should sing a favorite nursery rhyme.",
            "should try to balance on one foot for 10 seconds.",
            "should meow like a cat three times.",
            "should bark like a dog five times.",
            "should act like a chicken crossing the road.",
            "should do a silly dance for 30 seconds.",
            "should clap their hands 20 times as fast as possible.",
            "should jump up and down like a kangaroo.",
            "should count from 1 to 10 in a funny voice.",
            "should pretend to laugh like a villain.",
            "should draw an imaginary square in the air.",
            "should hum the first song that comes to mind.",
            "should pretend to be an airplane for 15 seconds.",
            "should spell a random word while hopping on one foot.",
            "should count how many times they can blink in 10 seconds.",
            "should name their favorite food and describe it in five words."

        };

            allInstructions = new List<string>
        {
            "should take three strikes.",
            "should each dance for one minute.",
            "should each crack a joke.",
            "should take five (5) press ups.",
            "should take five strikes.",
            "should hop like a big froggie! Haha!",
            "should each tell a secret",
            "should each sing the chorus of their favorite song.",
            "should all make their funniest face!",
            "should each act like their favorite animal.",
            "should take turns shouting a random word—no repeats!",
            "should clap their hands while hopping on one foot.",
            "should each impersonate someone famous!",
            "should all do a group dance—freestyle, of course!",
            "should each share their favorite snack choice.",
            "should all do their best evil laugh! Mwahaha!",
            "should try balancing something on their heads.",
            "should all say their name backward.",
            "should take a round of 'truth or dare'—no dodging!",
            "should each count to five in another language.",
            "should recite the alphabet… backward!",
            "should all do their best impression of a robot.",
            "should strike their best superhero pose!",
            "should each attempt a tongue twister!",
            "should create a short, funny rhyme together.",
            "should each mimic the sound of their favorite animal.",
            "should freeze like statues for a full 30 seconds.",
            "should each whistle their favorite tune—or try!",
            "should each say something nice about the person next to them.",
            "should each say something sad about the person next to them.",
            "should each say something nice about their favourite person.",
            "should make the loudest noise they can together!",
            "should each give their best pirate 'Arrrr!'",
            "should each give their best pirate 'Aye!'",
            "should all spin in circles until someone giggles.",
            "should do their best runway walk. Fierce!"
        };

        yourTurnTexts = new List<string>
        {
            "Oh! One good turn... Ha!",
            "Are you ready for this?",
            "Definitely up now, ain't ya?!",
            "Yoo.. You got this!",
            "Shoot pookie...",
            "Okay, let's have it.",
            "Bet you didn't see this coming",
            "Lucky you, haha!",
            "Here goes nothing!",
            "Oh dear, let's hear it!",
            "Can't wait, can you?",
            "Pook, shoot!",
            "The fun just got started",
            "Hey everyone, listen, you don't wanna miss this!",
            "The next victim is you, obviously! Haha!",
            "Oh snap, it's your moment! Make it count!",
            "Drumroll, please! You're up, superstar!",
            "Hold on to your hats, it's time to shine!",
            "Woohoo! All eyes on you now!",
            "Boom! Lights, camera, action!",
            "Ahh, destiny calls! Let's hear it!",
            "Are you feeling lucky? You better be!",
            "No pressure, but we're all watching!",
            "It's showtime, baby! Go for it!",
            "Ding ding ding! Your turn to dazzle!",
            "How're you feeling now?!",
            "Mic check... You're live!",
            "Ka-chow! Show us what you're made of!",
            "Whoa, the stage is all yours! Take it away!",

        };

         allPlayersTurnTexts = new List<string>
        {
            "Alright, folks! The spotlight's on all of you now—no hiding!",
            "Woohoo! It's everyone's time to shine! Let's hear it!",
            "Drumroll, please! This one's for all of you!",
            "Okay, gang, let's see what you've got together!",
            "Shoot y'all...",
            "Okay, let's have it.",
            "Bet y'all didn't see this coming",
            "Lucky folks, haha!",
            "Here goes nothing!",
            "Oh dear, let's hear it!",
            "Can't wait, can y'all?",
            "Pooks, shoot!",
            "The fun just got started",
            "Hey everyone, listen, you don't wanna miss yourselves!",
            "The next victim is everyone",
            "The floor is yours, squad! Make it epic!",
            "Y'all better bring the heat now! No slacking!",
            "Aha! It's a team effort this time. Go, go, go!",
            "The more, the merrier!",
            "Alright, party people! This question's for the entire crew!",
            "Time to huddle up, team! This one's for all of you!",
            "Okay, champs! Show us what happens when brains collide!",
            "Uh-oh, looks like everyone's in the hot seat this time!",
            "Brace yourselves, it's an all-hands-on-deck situation!",
            "Every last one of you—let's see the magic happen!",
            "It's an all-play extravaganza! Bring your A-game, everyone!",
            "Everybody's up! The pressure's shared—good luck!",
            "One question. All of you. Let's see what chaos ensues!",
            "Alright, squad, your turn as a team. Go make history!", 
        };
    }

    public string callQuestion()
    {
        int randomIndex = Random.Range(0, questions.Count);
        return questions[randomIndex];
    }

    public string callYourTurnText()
    {
        int randomIndex = Random.Range(0, yourTurnTexts.Count);
        return yourTurnTexts[randomIndex];
    }

    public string callInstructionText()
    {
        int randomIndex = Random.Range(0, instructions.Count);
        return instructions[randomIndex];
    }

        public string callAllInstructionText()
    {
        int randomIndex = Random.Range(0, allInstructions.Count);
        return allInstructions[randomIndex];
    }

     public string AllPlayersTurn()
    {
        int randomIndex = Random.Range(0, allPlayersTurnTexts.Count);
        return allPlayersTurnTexts[randomIndex];
    }
}
